import { readFileSync, readdirSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const promptDirectory = fileURLToPath(new URL("../prompts/", import.meta.url));
export const promptCatalogPath = fileURLToPath(
  new URL("../src/generated/prompt-catalog.ts", import.meta.url),
);

/** Canonical Markdown is the only source; output order is platform independent. */
export function renderPromptCatalog(): string {
  const entries: [string, string][] = [];
  function visit(relativeDirectory: string) {
    for (const entry of readdirSync(join(promptDirectory, relativeDirectory), {
      withFileTypes: true,
    })) {
      const relativePath = relativeDirectory
        ? `${relativeDirectory}/${entry.name}`
        : entry.name;
      if (entry.isDirectory()) visit(relativePath);
      else if (entry.isFile() && entry.name.endsWith(".md")) {
        const raw = readFileSync(join(promptDirectory, relativePath), "utf8");
        if (!raw.trim()) throw new Error(`Empty prompt: ${relativePath}`);
        entries.push([`/prompts/${relativePath}`, raw]);
      }
    }
  }
  visit("");
  entries.sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0));
  if (!entries.length) throw new Error("No prompt templates found.");
  return [
    "// Generated by scripts/compile-prompts.ts. Edit prompts/**/*.md instead.",
    "// Bundled for browser, Bun, and Convex; no runtime filesystem required.",
    "// prettier-ignore",
    "export const promptCatalog: Readonly<Record<string, string>> = {",
    ...entries.map(
      ([key, raw]) => `  ${JSON.stringify(key)}: ${JSON.stringify(raw)},`,
    ),
    "};",
    "",
  ].join("\n");
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.some((arg) => arg !== "--check")) {
    throw new Error("Usage: bun scripts/compile-prompts.ts [--check]");
  }
  const next = renderPromptCatalog();
  let current: string | undefined;
  try {
    current = readFileSync(promptCatalogPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  if (args.includes("--check")) {
    if (current !== next) {
      throw new Error("Prompt catalog is stale. Run bun run prompts:compile.");
    }
    console.log("Prompt catalog matches canonical Markdown.");
  } else if (current !== next) {
    mkdirSync(dirname(promptCatalogPath), { recursive: true });
    writeFileSync(promptCatalogPath, next);
    console.log("Compiled prompt catalog.");
  } else {
    console.log("Prompt catalog is current.");
  }
}
